download_url: https://galaxy.ansible.com/download/theforeman-operations-2.0.0.tar.gz
format_version: 1.0.0
name: operations
namespace: theforeman
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/theforeman/operations/versions/2.0.0/
