---

- hosts: "{{ target_host | default('localhost') }}"
  connection: local
  gather_facts: false

  vars:
    attributes:
      - MemTest: Disabled
      - LogicalProc: Enabled
      - SriovGlobalEnable: Disabled
      - ProcVirtualization: Enabled

  tasks:

  - name: Set BIOS attributes
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ item.key }}"
      bios_attr_value: "{{ item.value }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    loop: "{{ attributes }}"

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BootMode to Legacy BIOS
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: BootMode
      bios_attribute_value: Bios
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

  - name: Enable PXE Boot for NIC1
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: PxeDev1EnDis
      bios_attribute_value: Enabled
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

  # - name: Set BIOS default settings with a timeout of 20 seconds
  #   redfish_config:
  #     category: Systems
  #     command: SetBiosDefaultSettings
  #     baseuri: "{{ baseuri }}"
  #     username: "{{ username }}"
  #     password: "{{ password }}"
  #     timeout: 20

# redfish compatiblity
#
#iDRAC9
#4.40.00.00
#4.20.20.20
#4.00.00.00
#3.40.40.40
#3.36.36.36
#3.30.30.30
#3.21.21.21
#3.00.00.00
#
#iDRAC8
#2.70.70.70
#2.60.60.60
#2.40.40.40
#
#iLO
#5
#4
#3

## More will be added as module features are expanded
#CATEGORY_COMMANDS_ALL = {
#    "Systems": ["PowerOn", "PowerForceOff", "PowerForceRestart", "PowerGracefulRestart",
#                "PowerGracefulShutdown", "PowerReboot", "SetOneTimeBoot", "EnableContinuousBootOverride", "DisableBootOverride",
#                "IndicatorLedOn", "IndicatorLedOff", "IndicatorLedBlink"],
#    "Chassis": ["IndicatorLedOn", "IndicatorLedOff", "IndicatorLedBlink"],
#    "Accounts": ["AddUser", "EnableUser", "DeleteUser", "DisableUser",
#                 "UpdateUserRole", "UpdateUserPassword", "UpdateUserName",
#                 "UpdateAccountServiceProperties"],
#    "Sessions": ["ClearSessions", "CreateSession", "DeleteSession"],
#    "Manager": ["GracefulRestart", "ClearLogs", "VirtualMediaInsert",
#                "VirtualMediaEject", "PowerOn", "PowerForceOff", "PowerForceRestart",
#                "PowerGracefulRestart", "PowerGracefulShutdown", "PowerReboot"],
#    "Update": ["SimpleUpdate"]
#}

#  - name: Restart system power gracefully
#    redfish_command:
#      category: Systems
#      command: PowerGracefulRestart
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#
#  - name: Set one-time boot device to {{ bootdevice }}
#    redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      bootdevice: "{{ bootdevice }}"
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#
#  - name: Add and enable user
#    redfish_command:
#      category: Accounts
#      command: AddUser,EnableUser
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#      username: "{{ username }}"
#      userpswd: "{{ userpswd }}"
#      userrole: "{{ userrole }}"
#
#  - name: Disable and delete user
#    redfish_command:
#      category: Accounts
#      command: ["DisableUser", "DeleteUser"]
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#
#  - name: Update user password
#    redfish_command:
#      category: Accounts
#      command: UpdateUserPassword
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#      userpswd: "{{ userpswd }}"
#
#  - name: Turn system power off
#    community.general.redfish_command:
#      category: Systems
#      command: PowerForceOff
#      resource_id: 437XR1138R2
#
#  - name: Restart system power forcefully
#    community.general.redfish_command:
#      category: Systems
#      command: PowerForceRestart
#      resource_id: 437XR1138R2
#
#  - name: Shutdown system power gracefully
#    community.general.redfish_command:
#      category: Systems
#      command: PowerGracefulShutdown
#      resource_id: 437XR1138R2
#
#  - name: Turn system power on
#    community.general.redfish_command:
#      category: Systems
#      command: PowerOn
#      resource_id: 437XR1138R2
#
#  - name: Reboot system power
#    community.general.redfish_command:
#      category: Systems
#      command: PowerReboot
#      resource_id: 437XR1138R2
#
#  - name: Set one-time boot device to {{ bootdevice }}
#    community.general.redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      resource_id: 437XR1138R2
#      bootdevice: "{{ bootdevice }}"
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Set one-time boot device to UefiTarget of "/0x31/0x33/0x01/0x01"
#    community.general.redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      resource_id: 437XR1138R2
#      bootdevice: "UefiTarget"
#      uefi_target: "/0x31/0x33/0x01/0x01"
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Set one-time boot device to BootNext target of "Boot0001"
#    community.general.redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      resource_id: 437XR1138R2
#      bootdevice: "UefiBootNext"
#      boot_next: "Boot0001"
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Set persistent boot device override
#    community.general.redfish_command:
#      category: Systems
#      command: EnableContinuousBootOverride
#      resource_id: 437XR1138R2
#      bootdevice: "{{ bootdevice }}"
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Set one-time boot to BiosSetup
#    community.general.redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      boot_next: BiosSetup
#      boot_override_mode: Legacy
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Disable persistent boot device override
#    community.general.redfish_command:
#      category: Systems
#      command: DisableBootOverride
#
#  - name: Set system indicator LED to blink using security token for auth
#    community.general.redfish_command:
#      category: Systems
#      command: IndicatorLedBlink
#      resource_id: 437XR1138R2
#      baseuri: "{{ baseuri }}"
#      auth_token: "{{ result.session.token }}"
#
#  - name: Add user
#    community.general.redfish_command:
#      category: Accounts
#      command: AddUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      new_username: "{{ new_username }}"
#      new_password: "{{ new_password }}"
#      roleid: "{{ roleid }}"
#
#  - name: Add user using new option aliases
#    community.general.redfish_command:
#      category: Accounts
#      command: AddUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#      account_password: "{{ account_password }}"
#      account_roleid: "{{ account_roleid }}"
#
#  - name: Delete user
#    community.general.redfish_command:
#      category: Accounts
#      command: DeleteUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#
#  - name: Disable user
#    community.general.redfish_command:
#      category: Accounts
#      command: DisableUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#
#  - name: Enable user
#    community.general.redfish_command:
#      category: Accounts
#      command: EnableUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#
#  - name: Add and enable user
#    community.general.redfish_command:
#      category: Accounts
#      command: AddUser,EnableUser
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      new_username: "{{ new_username }}"
#      new_password: "{{ new_password }}"
#      roleid: "{{ roleid }}"
#
#  - name: Update user password
#    community.general.redfish_command:
#      category: Accounts
#      command: UpdateUserPassword
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#      account_password: "{{ account_password }}"
#
#  - name: Update user role
#    community.general.redfish_command:
#      category: Accounts
#      command: UpdateUserRole
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#      roleid: "{{ roleid }}"
#
#  - name: Update user name
#    community.general.redfish_command:
#      category: Accounts
#      command: UpdateUserName
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#      account_updatename: "{{ account_updatename }}"
#
#  - name: Update user name
#    community.general.redfish_command:
#      category: Accounts
#      command: UpdateUserName
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_username: "{{ account_username }}"
#      update_username: "{{ update_username }}"
#
#  - name: Update AccountService properties
#    community.general.redfish_command:
#      category: Accounts
#      command: UpdateAccountServiceProperties
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      account_properties:
#        AccountLockoutThreshold: 5
#        AccountLockoutDuration: 600
#
#  - name: Clear Manager Logs with a timeout of 20 seconds
#    community.general.redfish_command:
#      category: Manager
#      command: ClearLogs
#      resource_id: BMC
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      timeout: 20
#
#  - name: Create session
#    community.general.redfish_command:
#      category: Sessions
#      command: CreateSession
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#    register: result
#
#  - name: Set chassis indicator LED to blink using security token for auth
#    community.general.redfish_command:
#      category: Chassis
#      command: IndicatorLedBlink
#      resource_id: 1U
#      baseuri: "{{ baseuri }}"
#      auth_token: "{{ result.session.token }}"
#
#  - name: Delete session using security token created by CreateSesssion above
#    community.general.redfish_command:
#      category: Sessions
#      command: DeleteSession
#      baseuri: "{{ baseuri }}"
#      auth_token: "{{ result.session.token }}"
#      session_uri: "{{ result.session.uri }}"
#
#  - name: Clear Sessions
#    community.general.redfish_command:
#      category: Sessions
#      command: ClearSessions
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Simple update
#    community.general.redfish_command:
#      category: Update
#      command: SimpleUpdate
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      update_image_uri: https://example.com/myupdate.img
#
#  - name: Simple update with additional options
#    community.general.redfish_command:
#      category: Update
#      command: SimpleUpdate
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      update_image_uri: //example.com/myupdate.img
#      update_protocol: FTP
#      update_targets:
#        - /redfish/v1/UpdateService/FirmwareInventory/BMC
#      update_creds:
#        username: operator
#        password: supersecretpwd
#
#  - name: Insert Virtual Media
#    community.general.redfish_command:
#      category: Manager
#      command: VirtualMediaInsert
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      virtual_media:
#        image_url: 'http://example.com/images/SomeLinux-current.iso'
#        media_types:
#          - CD
#          - DVD
#      resource_id: BMC
#
#  - name: Eject Virtual Media
#    community.general.redfish_command:
#      category: Manager
#      command: VirtualMediaEject
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      virtual_media:
#        image_url: 'http://example.com/images/SomeLinux-current.iso'
#      resource_id: BMC
#
#  - name: Restart manager power gracefully
#    community.general.redfish_command:
#      category: Manager
#      command: GracefulRestart
#      resource_id: BMC
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#
#  - name: Restart manager power gracefully
#    community.general.redfish_command:
#      category: Manager
#      command: PowerGracefulRestart
#      resource_id: BMC
#
#  - name: Turn manager power off
#    community.general.redfish_command:
#      category: Manager
#      command: PowerForceOff
#      resource_id: BMC
#
#  - name: Restart manager power forcefully
#    community.general.redfish_command:
#      category: Manager
#      command: PowerForceRestart
#      resource_id: BMC
#
#  - name: Shutdown manager power gracefully
#    community.general.redfish_command:
#      category: Manager
#      command: PowerGracefulShutdown
#      resource_id: BMC
#
#  - name: Turn manager power on
#    community.general.redfish_command:
#      category: Manager
#      command: PowerOn
#      resource_id: BMC
#
#  - name: Reboot manager power
#    community.general.redfish_command:
#      category: Manager
#      command: PowerReboot
#      resource_id: BMC
