---

- hosts: "{{ target_host | default('localhost') }}"
  connection: local
  gather_facts: false

  vars:
    attributes:
      - MemTest: Disabled
      - LogicalProc: Enabled
      - SriovGlobalEnable: Disabled
      - ProcVirtualization: Enabled

  tasks:

  - name: Set BIOS attributes
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ item.key }}"
      bios_attr_value: "{{ item.value }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    loop: "{{ attributes }}"

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BootMode to Legacy BIOS
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: BootMode
      bios_attribute_value: Bios
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

  - name: Enable PXE Boot for NIC1
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: PxeDev1EnDis
      bios_attribute_value: Enabled
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

  # - name: Set BIOS default settings with a timeout of 20 seconds
  #   redfish_config:
  #     category: Systems
  #     command: SetBiosDefaultSettings
  #     baseuri: "{{ baseuri }}"
  #     username: "{{ username }}"
  #     password: "{{ password }}"
  #     timeout: 20
  
# redfish compatiblity
#
#iDRAC9
#4.40.00.00
#4.20.20.20
#4.00.00.00
#3.40.40.40
#3.36.36.36
#3.30.30.30
#3.21.21.21
#3.00.00.00
#
#iDRAC8
#2.70.70.70
#2.60.60.60
#2.40.40.40

#  - name: Restart system power gracefully
#    redfish_command:
#      category: Systems
#      command: PowerGracefulRestart
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#
#  - name: Set one-time boot device to {{ bootdevice }}
#    redfish_command:
#      category: Systems
#      command: SetOneTimeBoot
#      bootdevice: "{{ bootdevice }}"
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#
#  - name: Add and enable user
#    redfish_command:
#      category: Accounts
#      command: AddUser,EnableUser
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#      username: "{{ username }}"
#      userpswd: "{{ userpswd }}"
#      userrole: "{{ userrole }}"
#
#  - name: Disable and delete user
#    redfish_command:
#      category: Accounts
#      command: ["DisableUser", "DeleteUser"]
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#
#  - name: Update user password
#    redfish_command:
#      category: Accounts
#      command: UpdateUserPassword
#      baseuri: "{{ baseuri }}"
#      user: "{{ user }}"
#      password: "{{ password }}"
#      userid: "{{ userid }}"
#      userpswd: "{{ userpswd }}"

